FROM ubuntu:22.04

WORKDIR /opt/CavaCloudServer/teu
COPY teu /opt/CavaCloudServer/teu/
COPY common/*.sh /opt/CavaCloudServer/teu/
RUN sh change2bash.sh
RUN sh changezone.sh
RUN sh fix_ubuntu_han.sh \
    && apt-get install -y git curl\
    && sh cava3_debian_install.sh

ENTRYPOINT ["/opt/CavaCloudServer/teu/cava_teu"]
