FROM cava3_base:1.0.0

WORKDIR /usr/local/redis
COPY redis /usr/local/redis/
RUN cd bin \
    && chmod 755 libatomic.so.* \ 
    && cp -rf libatomic.so.* /usr/lib/aarch64-linux-gnu/

ENTRYPOINT ["/usr/local/redis/bin/redis-server", "/usr/local/redis/conf/redis.conf"]
