FROM ubuntu:22.04

WORKDIR /opt/cavaopenapi
COPY cavaopenapi /opt/cavaopenapi/
COPY common/*.sh /opt/cavaopenapi/
RUN sh change2bash.sh
RUN sh changezone.sh
RUN sh fix_ubuntu_han.sh

ENTRYPOINT ["/opt/cavaopenapi/CavaOpenAPI"]
