FROM ubuntu:22.04

WORKDIR /opt/CavaOpenClient
COPY CavaOpenClient /opt/CavaOpenClient/
COPY common/*.sh /opt/CavaOpenClient/
RUN sh change2bash.sh
RUN sh changesrc.sh
RUN sh changezone.sh
RUN sh fix_ubuntu_han.sh \
    && apt-get install -y cron

ENTRYPOINT ["/opt/CavaOpenClient/init.sh"]
